# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # Python paket güncellemeleri
    directory: "/" # Requirements.txt'in bulunduğu dizin
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions" # GitHub Actions güncellemeleri
    directory: "/" # Workflow dosyalarının bulunduğu dizin
    schedule:
      interval: "monthly"
